# FCSIT AdvisorBot API Backend
#
# Requirements:
#   pip install fastapi uvicorn python-dotenv
#   (plus all existing RAG pipeline dependencies)
#
# Run locally:
#   python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload 
#


from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional
import logging
import traceback
import time

# ==============================
# IMPORT YOUR EXISTING PIPELINE
# ==============================


from vector_rag import route_query, intent_chain

# ==============================
# LOGGING
# ==============================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

# ==============================
# APP INITIALISATION
# ==============================

app = FastAPI(
    title="AdvisorBot API",
    description="RAG-powered academic advising chatbot API for FCSIT UNIMAS.",
    version="1.0.0"
)

# CORS — allows your Flutter app (and any local browser testing) to call this API.
# During development, allow all origins for convenience.
# Tighten this to specific origins before production deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==============================
# REQUEST / RESPONSE MODELS
# ==============================

class QueryRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="The user's query to the academic advising chatbot.",
        examples=["What are the programmes offered by FCSIT UNIMAS?"]
    ) 

class QueryResponse(BaseModel):
    answer: str = Field(description="The chatbot's response.")
    intent: Optional[str] = Field(
        default=None,
        description="The detected intent category of the query."
    )
    response_time_s: float = Field(
        description="Time taken by the AI to generate the answer, in seconds."
    )

class HealthResponse(BaseModel):
    status: str
    message: str

# ==============================
# HELPER — DETECT INTENT
# ==============================


def detect_intent(question: str) -> str:
    try:
        intent = intent_chain.invoke({"question": question}).strip().lower()
        return intent
    except Exception:
        return "unknown"

# ==============================
# ROUTES
# ==============================

@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Health check",
    description="Check that the API and RAG pipeline are running correctly."
)
async def health_check():
    return HealthResponse(
        status="ok",
        message="AdvisorBot API is running."
    )


@app.post(
    "/query",
    response_model=QueryResponse,
    summary="Send a query to AdvisorBot",
    description=(
        "Accepts a natural language question and returns an answer "
        "generated by the RAG pipeline."
    )
)
async def query(request: QueryRequest):

    logger.info(f"Received query: {request.question!r}")
    start_time = time.perf_counter()

    try:
        # Detect intent for response metadata
        intent = detect_intent(request.question)
        logger.info(f"Detected intent: {intent}")

        # Route through the existing pipeline
        result = route_query(request.question)
        logger.info("Query answered successfully.")
        logger.info(f"Answer: {result['answer']!r}")

        elapsed_s = time.perf_counter() - start_time
        logger.info(f"Response time: {elapsed_s:.2f} s")

        return QueryResponse(
            answer=result["answer"],
            intent=intent,
            response_time_s=elapsed_s,
        )

    except Exception:
        elapsed_s = time.perf_counter() - start_time
        logger.error(f"Response time before failure: {elapsed_s:.2f} s")
        logger.error(f"Error processing query: {traceback.format_exc()}")
        # Return a 500 with a descriptive message.
        # Do NOT expose raw exception details to the client in production.
        raise HTTPException(
            status_code=500,
            detail="An internal error occurred while processing your query. "
                   "Please try again."
        )


